// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://khmytjiytpgpkccwncvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobXl0aml5dHBncGtjY3duY3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTUxOTMsImV4cCI6MjA3MjU5MTE5M30.Mtat_70w7LW-jHsuVicCsywVxU49kgQ0t15fXPq2Wxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});